### ISSUE TITLE
not issue: Want to thank you

### ISSUE THREAD

**Issue by Reunion31** [pons-deluxe/kanji-unlock-addon#1]
Hello, I haven't found a place on Github where I can thank you for your work. Let me say that with this addon you've saved me a lot of time. I don't have to go over every single word trying to find new kanji. Instead, I just learn some vocabulary, unlock the kanji and keep learning seamlessly. I've rated your addon on Anki addons, but I wanted it to be here too. I'm very grateful for your work. You're a gentleman and a scholar.

Also, I've noticed that the unlocked kanji (not vocab with kanji) don't receive any tags. Could you implement it, so that when a kanji gets unlocked, it also gets tagged by something like "kanjiunlocked_kanji"?

**Comment by pons-deluxe** [comment]
I'm glad you find it useful! Thanks for rating the addon on the addons website!

The tag for the kanji is a good idea, it could solve a potential issue where cards you _want_ to be suspended keep getting unsuspended if they appear in new words. I'll create a new issue for it. Hopefully I can get to it before long
